[package]
name = "telemetry-sqs-to-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { version = "1.0.0", default-features = false, features = ["sqs"] }

lambda_runtime = "1.0.1"
serde_json = "1.0.149"
tokio = { version = "1", features = ["macros"] }
